name: Cài đặt theo link ISO tuỳ chỉnh
run-name: Chào mừng ${{ github.actor }} 🚀

on:

  workflow_dispatch:
   inputs:
      
      os4:
        description: 'Nhập link Direct Trực tiếp tới file ISO '
        required: true
      os5:
        description: 'Nhập số GB dung lượng cần thiết cho ổ đĩa Windows. Ví dụ: 500G'
        required: true
      os6:
        description: 'Số M ram cần thiết. Ví dụ: 2048M'
        required: true
      
    

jobs:

  Dang_Chay:

    timeout-minutes: 360

    runs-on: self-hosted 

    

    steps:

    - name: Đang chạy...

      run: |

            sleep 1
            echo Đang cài đặt
            sudo apt update &>/dev/null
            sudo apt install qemu-utils qemu-system-x86 -y &>/dev/null
            echo Đang tải file Windows...
            wget -O windows.iso ${{ github.event.inputs.os4 }} &>/dev/null
            echo Đang tạo file đĩa theo ý của bạn
            qemu-img create -f raw windows.img ${{ github.event.inputs.os5 }}
            
            echo Đã chạy thành công!!!!!!!
            echo Để kết nối hãy mở VNC lên và vào localhost:0
            echo Để kết nối với Remote Desktop hãy vào máy Windows vừa tạo và bật Remote Desktop lên, quay lại Linux gốc và kết nối vào localhost:3381
            qemu-system-x86_64 -net nic -net user,hostfwd=tcp::3381-:3389 -m ${{ github.event.inputs.os5 }} -device usb-tablet -device usb-ehci,id=usb,bus=pci.0,addr=0x4 -cpu max,+nx -smp 2 -usbdevice tablet -k en-us -cdrom windows.iso -hda windows.img -vnc :0 -boot d
      timeout-minutes: 99999999999999999999999999999999999999999
